import { Toaster } from 'react-hot-toast';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from 'next/image';
import AboutSection from "./_components/AboutSection";
import AbouttSection from "./_components/AbouttSection";
import Services from "./_components/Services";
import OurTeam from "./_components/OurTeam";
import ContactForm from "./_components/ContactForm";
import Footer from "./_components/footer";
import Navbar from "./_components/Navbar";
import HeroSection from "./_components/HeroSection";
import ContactPage from "./_components/ContactForm";
import WorkSection from './_components/Works';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CodeScope",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className="relative"
      >
        
        {children}

      </body>
    </html>
  );
}
